"
A TestGrinderTest is a test class for testing the behavior of TestGrinder
"
Class {
	#name : #SmallMinceTest,
	#superclass : #TestCase,
	#category : #'SmallMince-Tests-0.Core'
}

{ #category : #tests }
SmallMinceTest >> testSystem_ExampleMario [

	SmallMince exampleMario
]

{ #category : #tests }
SmallMinceTest >> testSystem_ExampleSCAMPaper [

	SmallMince exampleSCAMPaper
]

{ #category : #tests }
SmallMinceTest >> testSystem_ExampleSCAMPaper2 [

	SmallMince exampleSCAMPaper2
]

{ #category : #tests }
SmallMinceTest >> testSystem_ExampleSCAMPaper3 [

	SmallMince exampleSCAMPaper3
]

{ #category : #tests }
SmallMinceTest >> testSystem_ExampleSCAMPaper4 [

	SmallMince exampleSCAMPaper4
]
